language: node_js
node_js: stable

script:
  - yarn
  - yarn build

after_script:
  - cd ./build
  - git init
  - git config user.name "JimmyBenKlieve"
  - git config user.email "j.b.klieve@live.cn"
  - git add .
  - git commit -m "update website"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source

env:
  global:
    - GH_REF: "github.com/JimmyBenKlieve/jimmybenklieve.github.io.git"
