language: node_js
node_js: stable

before_script:
  - wget "http://music.163.com/api/playlist/detail?id=427756070" -O "./music-list.json"
  - ls

script:

after_script:
  - git config user.name "JimmyBenKlieve"
  - git config user.email "j.b.klieve@live.cn"
  - git add .
  - git commit -m "Refresh music list"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" origin:master

branches:
  only:
    - source

env:
  global:
    - GH_REF: "github.com/JimmyBenKlieve/jimmybenklieve.github.io.git"
