# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Use Yarn
      uses: CultureHQ/actions-yarn@v1.0.1
    
    # - name: Install expect
    #  run: sudo apt-get -y install expect
    
    - name: Build
      run: |
        yarn
        yarn build
        mv ./build ./un1code.xyz
        tar -zcvf web.tar un1c0de.xyz
  
    # - name: Deploy
    #  run: bash $GITHUB_WORKSPACE/scripts/deploy.sh
    #  env: 
    #    REMOTE_IP: ${{ secrets.REMOTE_IP }}
    #    REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #    REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: web-build-artifact
        path: ./web.tar
